[2022-05-26 18:55:41,298] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.merge_data scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 18:55:41,305] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.merge_data scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2022-05-26 18:55:41,306] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 18:55:41,306] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-26 18:55:41,306] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-26 18:55:41,315] {taskinstance.py:1378} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2022-05-25 00:00:00+00:00
[2022-05-26 18:55:41,318] {standard_task_runner.py:52} INFO - Started process 9217 to run task
[2022-05-26 18:55:41,320] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Etl', 'merge_data', 'scheduled__2022-05-25T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmph5k4swf2', '--error-file', '/tmp/tmpq3sj4v50']
[2022-05-26 18:55:41,320] {standard_task_runner.py:80} INFO - Job 24: Subtask merge_data
[2022-05-26 18:55:41,361] {task_command.py:370} INFO - Running <TaskInstance: Etl.merge_data scheduled__2022-05-25T00:00:00+00:00 [running]> on host b7bcf2b221fa
[2022-05-26 18:55:41,418] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Etl
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-25T00:00:00+00:00
[2022-05-26 18:55:41,424] {base.py:68} INFO - Using connection ID 'tutorial_pg_conn' for task execution.
[2022-05-26 18:55:41,426] {python.py:173} INFO - Done. Returned value was: 1
[2022-05-26 18:55:41,449] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=Etl, task_id=merge_data, execution_date=20220525T000000, start_date=20220526T185541, end_date=20220526T185541
[2022-05-26 18:55:41,492] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-26 18:55:41,513] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
